timeStat[1]=new Date() - timeStat[0];
var G={index:{}};
(function(d){var m=function(a,e){var b=document.createElement("script");b.type="text/javascript";b.src=a;b.onload=e;document.getElementsByTagName("head")[0].appendChild(b)},k=d.fstfs;if(k&&0!==k.length){

	var f=d.G.index,g;f.getCookie=function(a){return(a=document.cookie.match(RegExp("(^| )"+a+"(?:=([^;]*))?(;|$)")))?a[2]?unescape(a[2]):"":""};g=f.data={siteId:G.index.getCookie("wsid")||"1",areaId:(G.index.getCookie("loc")||"2").split("_")[0]||"2",uin:function(){var a;a=G.index.getCookie;a=a("yx_uin")||
a("uin")||"";return a="&uin="+a.replace(/^o/,"")}()};g="&type=jsonp&skey="+g.areaId+"&wsid="+g.siteId+g.uin;d.rStart=(new Date).getTime();timeStat[4]=new Date-timeStat[0];m(d.rMsUrl+g+"&callback=adHandler&tcdn=1");m(d.rQbUrl+g+"&callback=goodsHandler&tcdn=1");var f=d.G.index,p=function(a){var e=a.EXTDATA?a.EXTDATA:{},b,c;"string"==typeof e&&(0!=e.indexOf("{")&&(e="{"+e+"}"),e=f.jsonparser(e));
if((c=parseInt(e.inventory,10))&&(b=parseInt(a.INVENTORY,10)))a.STOCKPERCENT=(b/c).toFixed(2);if(e.PROTYPE&&e.PROCOUNT&&(b=(e.PROCOUNT.match(/\d+/)||[])[0],c=["用券减","下单减","已降"],e=parseInt(e.PROTYPE),b&&1E4>b&&(e=c[e-1])))a.SHORT_PROMOTE=e+"<br />"+b+"元",a.CLASSNAME="mod_goods_mark_1";return!0};f.jsonparser=function(a){return"undefined"!==typeof JSON&&JSON.parse?JSON.parse(a):(new Function("return"+a.replace(/^\s+/,"")+";"))()};f.decorateData=function(a,e){return a.PRICE?this.decGoodsData(a,e):this.decAdsData(a,
e)};f.picHandler=function(){var a;a={getPicUrl:function(a,b,c){var d=a.split("R",2);a=d[0];var d=a.split("-",3),f=d[0],h=d[1];return"http://img"+(parseInt(d[2])%2?"1":"2")+".icson.com/product/"+b+"/"+f+"/"+h+"/"+a+(0==c?"":"-"+(10>c?"0"+c:c))+".jpg"},getPicByPic:function(a,b){return 0==b?(a+"").replace(/(jpg|gif|png|bmp)\/\d+(\?\w+)?$/,"$1/"+b+"$2").replace(/qqbuy/,"51buypic"):(a+"").replace(/(jpg|gif|png|bmp)\/\d+(\?\w+)?$/,"$1/"+b+"$2")},getYXPicBySize:function(a,b){var c=[0,30,60,80,120,160,200,
300,400,600,800];-1<a.indexOf("icson.com")&&(c=[50,60,80,120,160,200,300,600,800]);for(var d=!1,f=0;f<c.length;f++)if(b==c[f]){d=!0;break}return d?(c="",-1<a.indexOf("wgimg.com")?c=this.getPicByPic(a,800==b?0:b):-1<a.indexOf("paipaiimg.com")?c=a.replace(/(\.)\d+x\d+(\.jpg|gif|png|bmp)?$/,"$1"+(b+"x"+b)+"$2"):-1<a.indexOf("icson.com")&&(c=a.replace(/\/product\/\w+\//,"/product/"+this.icsonExistMap[""+b]+"/")),c):c.join(",")},getIcsonPicBySize:function(a,b,c){var d=this.icsonExistMap;if(""+c in d)return this.getPicUrl(a,
d[""+c],b);a=[];for(var f in d)a.push(f);return a.join(",")},icsonExistMap:{50:"ss",60:"pic60",80:"small",120:"middle",160:"pic160",200:"pic200",300:"mm",800:"mpic"}};return{getPicBySize:function(){if(2==arguments.length)return a.getYXPicBySize.apply(a,arguments);if(3==arguments.length)return a.getIcsonPicBySize.apply(a,arguments)}}}();f.getPicUrl=function(a){var d,b=f.picHandler.getPicBySize;if(d=a.IMG)a.pic120=b(d,120),a.pic80=b(d,80)};f.decGoodsData=function(a,d){var b=a.AREA_STOCK_INFO?this.jsonparser(a.AREA_STOCK_INFO):
{},c;if(b=b[this.data.siteId])c=b.multiInfo||{},c=c["3:3"]||{},a.PRICE=c.mPrice?(c.mPrice/100).toFixed(2):b.price?(b.price/100).toFixed(2):a.PRICE;c=a.PROMOTE;a.TITCLASS="mod_goods_promo";if(!c||""==c||7>c.length)a.PROMOTE=a.TITLE,a.TITCLASS="mod_goods_tit";a.URL=a.URL.replace(/51buy\.com/,"#");this.getPicUrl(a);return"function"===typeof d?d(a,b):!0};f.decAdsData=function(a,d){var b=a.EXTDATA?a.EXTDATA:{},c;"string"==typeof b&&(0!=b.indexOf("{")&&(b="{"+b+"}"),b=this.jsonparser(b));if((c=
b.list)&&(c=c[0]))for(var f in c)a[f]=c[f];a.url=a.url.replace(/51buy\.com/,"#");return"function"===typeof d?d(a):!0};d.adHandler=function(a){if(!1!==d._ADTFRESULT){var e=(new Date).getTime(),b,c;if(a&&0==a.iRet&&(b=a.data)&&(b=b.POS_1)&&0<b.length){var g="10001",n=[];c=1;for(var h=0,k=b.length;h<k;h++){var l=b[h];l.src=0==h?"src":"_src";l.show=0==h?"":"hide";f.decAdsData(l);n.push('<li class="{show}"><a target="_blank" href="{url}" title="{title}" ytag="{ytag}"><img {src}="{picUrl}" alt="{title}" /></a></li>'.replace(/\{(\w+)\}/g,
function(a,b){return"ytag"==b?g++:l[b]||""}))}document.getElementById("POS_1_"+a.tfId).innerHTML=n.join("");d._ADTFRESULT=!0}else c=2,d._ADTFRESULT=!1;(new Image).src="http://c.isdspeed.qq.com/code.cgi?domain=s1.smarty.51buy.com&cgi="+encodeURIComponent(d.rMsUrl)+"&type="+c+"&code="+a.iRet+"&time="+(e-d.rStart)+"&rate=1";"undefined"!=typeof d._GDSTFRESULT&&(timeStat[5]=new Date-timeStat[0])}};d.goodsHandler=function(a){if(!1!==d._GDSTFRESULT){var e=(new Date).getTime(),b,c;if(a&&0==a.iRet&&(b=a.data)&&
(b=b.POS_1)&&0<b.length){var g="19001",k=[];c=1;for(var h=0,m=b.length;h<m;h++){var l=b[h];f.decGoodsData(l,p);k.push('<li>\t\t\t\t\t\t<div class="mod_goods mod_goods_w100" _loaded="true">\t\t\t\t\t\t\t<div class="mod_goods_img load_effect">\t\t\t\t\t\t\t\t<a href="{URL}" target="_blank" title="{TITLE}" ytag="{ytag}"><img src="{pic120}" alt="{TITLE}" /><b class="hide {CLASSNAME}">{SHORT_PROMOTE}</b></a>\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t<div class="mod_goods_info">\t\t\t\t\t\t\t\t<p class="mod_goods_tit"><a href="{URL}" target="_blank" title="{TITLE}" ytag="{ytag}">{PROMOTE}</a></p>\t\t\t\t\t\t\t\t<p class="mod_goods_price"><a href="{URL}" target="_blank" title="{TITLE}" ytag="{ytag}"><span class="mod_price mod_price_now"><i>&yen;</i><span>{PRICE}</span></span></a></p>\t\t\t\t\t\t\t\t<div class="mod_goods_stock">\t\t\t\t\t\t\t\t\t<a href="{URL}" target="_blank" title="{TITLE}" ytag="{ytag}"><em>库存</em>\t\t\t\t\t\t\t\t\t<span><i class="mod_goods_stock_bg2" w={STOCKPERCENT} style="width:100%"></i></span></a>\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t<p class="dailybeta_goods_btn_wrap">\t\t\t\t\t\t\t\t\t<a href="javascript:void(0)" class="dailybeta_goods_btn" pid="{COMMODITYID}" title="立即抢" ytag="{ytag}">立即抢</a>\t\t\t\t\t\t\t\t</p>\t\t\t\t\t\t\t</div>\t\t\t\t\t\t</div>\t\t\t\t\t</li>'.replace(/\{(\w+)\}/g,
function(a,b){return"ytag"==b?g++:l[b]||""}))}document.getElementById("POS_1_"+a.tfId).innerHTML=k.join("");d._GDSTFRESULT=!0}else c=2,d._GDSTFRESULT=!1;(new Image).src="http://c.isdspeed.qq.com/code.cgi?domain=s1.smarty.51buy.com&cgi="+encodeURIComponent(d.rQbUrl)+"&type="+c+"&code="+a.iRet+"&time="+(e-d.rStart)+"&rate=1";"undefined"!=typeof d._ADTFRESULT&&(timeStat[5]=new Date-timeStat[0])}}}})(window);<!--[if !IE]>|xGv00|c2db8551b7fb96c369f60b3947d3804e<![endif]-->