<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '食品、零食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => '32',
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '洋酒、葡萄酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => '30',
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => '工艺品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '2',
    'goods_num' => '31',
  ),
  3 => 
  array (
    'cat_id' => '9',
    'cat_name' => '家电电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => '30',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '美妆、化妆品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => '31',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '家居、家具、厨具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '8',
    'goods_num' => '31',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '服饰鞋帽',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => '31',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '个护化妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '国外箱包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => '32',
  ),
  9 => 
  array (
    'cat_id' => '10',
    'cat_name' => '母婴、玩具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '11',
    'cat_name' => '食品饮料、保健食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '12',
    'cat_name' => '彩票、旅行、充值',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '154',
    'cat_name' => '汽车用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '16',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '405',
    'cat_name' => '欧 洲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '418',
    'cat_name' => '非 洲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '396',
    'cat_name' => '亚 洲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '12',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '422',
    'cat_name' => '北美',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '415',
    'cat_name' => '澳洲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '432',
    'cat_name' => '南美',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '13',
    'cat_name' => '坚果果仁',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => '2',
  ),
  20 => 
  array (
    'cat_id' => '316',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '75',
    'cat_name' => '罐头',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '54',
    'cat_name' => '零食',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '9',
  ),
  23 => 
  array (
    'cat_id' => '395',
    'cat_name' => '棒棒糖',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '22',
    'cat_name' => '饼干糕点',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '69',
    'cat_name' => '饮料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '80',
    'cat_name' => '红普通酒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '106',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '123',
    'cat_name' => '洋酒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '8',
    'goods_num' => '8',
  ),
  29 => 
  array (
    'cat_id' => '93',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '171',
    'cat_name' => '特色工艺品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '200',
    'cat_name' => '装饰品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '208',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '212',
    'cat_name' => '彩妆',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '224',
    'cat_name' => '香氛',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '220',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '232',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '245',
    'cat_name' => '家装建材',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '242',
    'cat_name' => '生活日用',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '236',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '243',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '240',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '244',
    'cat_name' => '宠物用品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '241',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '246',
    'cat_name' => '个护化妆',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '250',
    'cat_name' => '鞋靴箱包',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '257',
    'cat_name' => '时尚搭配',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '254',
    'cat_name' => '女士健康',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '258',
    'cat_name' => '棉服',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '255',
    'cat_name' => '内衣',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '256',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '269',
    'cat_name' => '男士护理',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '267',
    'cat_name' => '运动户外',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '271',
    'cat_name' => '香水SPA',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '268',
    'cat_name' => '女性护理',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '259',
    'cat_name' => '营养健康',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '1',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '263',
    'cat_name' => '型男搭配',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '270',
    'cat_name' => '魅力彩妆',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '272',
    'cat_name' => '潮流女包',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '362',
    'cat_name' => '男士包',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '279',
    'cat_name' => '功能箱包',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '288',
    'cat_name' => '大家电',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '285',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '287',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '130',
    'cat_name' => '健康电器',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '298',
    'cat_name' => '寝具服饰',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '295',
    'cat_name' => '喂养用品',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '292',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '299',
    'cat_name' => '妈妈专区',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '296',
    'cat_name' => '洗护用品',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '293',
    'cat_name' => '营养辅食',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '300',
    'cat_name' => '玩具乐器',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '297',
    'cat_name' => '童车童床',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '294',
    'cat_name' => '尿裤湿巾',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '301',
    'cat_name' => '进口食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '308',
    'cat_name' => '健康礼品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '305',
    'cat_name' => '酒饮冲调',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '302',
    'cat_name' => '地方特产',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '309',
    'cat_name' => '生鲜食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '306',
    'cat_name' => '营养健康',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '303',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '307',
    'cat_name' => '亚健康',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '304',
    'cat_name' => '粮油调味',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  83 => 
  array (
    'cat_id' => '314',
    'cat_name' => '票务',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '311',
    'cat_name' => '机票',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '312',
    'cat_name' => '酒店',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '313',
    'cat_name' => '充值',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '310',
    'cat_name' => '彩票',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '14',
    'cat_name' => '坚果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '30',
  ),
  89 => 
  array (
    'cat_id' => '15',
    'cat_name' => '果仁',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '24',
  ),
  90 => 
  array (
    'cat_id' => '16',
    'cat_name' => '开心果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '20',
  ),
  91 => 
  array (
    'cat_id' => '17',
    'cat_name' => '腰果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 24,
  ),
  92 => 
  array (
    'cat_id' => '330',
    'cat_name' => '杏仁',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
  ),
  93 => 
  array (
    'cat_id' => '331',
    'cat_name' => '夏威夷果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '24',
  ),
  94 => 
  array (
    'cat_id' => '332',
    'cat_name' => '混合坚果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '27',
  ),
  95 => 
  array (
    'cat_id' => '339',
    'cat_name' => '威化饼',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '26',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  97 => 
  array (
    'cat_id' => '23',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '27',
    'cat_name' => '西式糕点',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '24',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '25',
    'cat_name' => '巧克力派',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
  ),
  101 => 
  array (
    'cat_id' => '59',
    'cat_name' => '薯片',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '55',
    'cat_name' => '海鲜零食',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '60',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '56',
    'cat_name' => '肉脯肉松',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '58',
    'cat_name' => '膨化类',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '73',
    'cat_name' => '豆浆',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '342',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '70',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '74',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '71',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '72',
    'cat_name' => '早餐谷物',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  112 => 
  array (
    'cat_id' => '79',
    'cat_name' => '鱼罐头',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
  ),
  113 => 
  array (
    'cat_id' => '76',
    'cat_name' => '鱼子酱',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
  ),
  114 => 
  array (
    'cat_id' => '77',
    'cat_name' => '果酱',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
  ),
  115 => 
  array (
    'cat_id' => '340',
    'cat_name' => '咖喱',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
  ),
  116 => 
  array (
    'cat_id' => '78',
    'cat_name' => '肉罐头',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
  ),
  117 => 
  array (
    'cat_id' => '341',
    'cat_name' => '水果罐头',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '81',
    'cat_name' => '干红',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '19',
  ),
  119 => 
  array (
    'cat_id' => '85',
    'cat_name' => '半干红',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  120 => 
  array (
    'cat_id' => '84',
    'cat_name' => '甜红',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '82',
    'cat_name' => '半甜红',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  122 => 
  array (
    'cat_id' => '99',
    'cat_name' => '黑啤',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '102',
    'cat_name' => '普通啤酒',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  124 => 
  array (
    'cat_id' => '111',
    'cat_name' => '干白',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  125 => 
  array (
    'cat_id' => '108',
    'cat_name' => '半干白',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  126 => 
  array (
    'cat_id' => '121',
    'cat_name' => '甜白',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '118',
    'cat_name' => '半甜白',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '124',
    'cat_name' => '白兰地',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  129 => 
  array (
    'cat_id' => '128',
    'cat_name' => '伏特加',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '127',
    'cat_name' => '威士忌',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '126',
    'cat_name' => '龙舌兰',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '125',
    'cat_name' => '金酒',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '129',
    'cat_name' => '朗姆酒',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '344',
    'cat_name' => '清酒',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '343',
    'cat_name' => '烧酒',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '394',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '139',
    'cat_name' => '其它健康电器',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '136',
    'cat_name' => '血糖仪',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '133',
    'cat_name' => '足浴盆',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '137',
    'cat_name' => '体温计',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '134',
    'cat_name' => '血压计',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  142 => 
  array (
    'cat_id' => '131',
    'cat_name' => '按摩器',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '138',
    'cat_name' => '计步器/脂肪检测仪',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '135',
    'cat_name' => '健康秤/厨房秤',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '132',
    'cat_name' => '按摩椅',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '161',
    'cat_name' => '脚垫',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '158',
    'cat_name' => '车载电源',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '155',
    'cat_name' => 'GPS',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  149 => 
  array (
    'cat_id' => '168',
    'cat_name' => '安全座椅',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '165',
    'cat_name' => '内饰',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '162',
    'cat_name' => '座垫座套',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '159',
    'cat_name' => '充气/吸尘',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '156',
    'cat_name' => '电子影音',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '169',
    'cat_name' => '自驾装备',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '166',
    'cat_name' => '配件',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '163',
    'cat_name' => '养护',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '160',
    'cat_name' => '冷暖箱',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '157',
    'cat_name' => '车载电器',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '170',
    'cat_name' => '安全/应急',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  160 => 
  array (
    'cat_id' => '167',
    'cat_name' => '香水/净化',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '164',
    'cat_name' => '美容',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '174',
    'cat_name' => '木质工艺品',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '345',
    'cat_name' => '手工艺品',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '172',
    'cat_name' => '金属工艺品',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '173',
    'cat_name' => '瓷器',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '205',
    'cat_name' => '地毯',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '207',
    'cat_name' => '装饰器具',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '202',
    'cat_name' => '挂饰',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '206',
    'cat_name' => '坐垫',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '203',
    'cat_name' => '编织装饰',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '210',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '348',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '211',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '349',
    'cat_name' => '护肤套装',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '346',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '350',
    'cat_name' => '化妆水',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '209',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '347',
    'cat_name' => '眼霜',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '354',
    'cat_name' => '唇彩',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '213',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '351',
    'cat_name' => '粉饼',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '355',
    'cat_name' => '彩妆套装',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '214',
    'cat_name' => 'BB霜',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '352',
    'cat_name' => '眼影',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  185 => 
  array (
    'cat_id' => '215',
    'cat_name' => '卸妆',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '353',
    'cat_name' => '睫毛膏',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  187 => 
  array (
    'cat_id' => '222',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  188 => 
  array (
    'cat_id' => '357',
    'cat_name' => '脱毛',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  189 => 
  array (
    'cat_id' => '223',
    'cat_name' => '润肤乳',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  190 => 
  array (
    'cat_id' => '358',
    'cat_name' => '护理套装',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  191 => 
  array (
    'cat_id' => '221',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  192 => 
  array (
    'cat_id' => '324',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  193 => 
  array (
    'cat_id' => '225',
    'cat_name' => '打印机',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  194 => 
  array (
    'cat_id' => '226',
    'cat_name' => '女士香水',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  195 => 
  array (
    'cat_id' => '356',
    'cat_name' => '香水套装',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  196 => 
  array (
    'cat_id' => '227',
    'cat_name' => '中性香水',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  197 => 
  array (
    'cat_id' => '235',
    'cat_name' => '收纳保鲜',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  198 => 
  array (
    'cat_id' => '233',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  199 => 
  array (
    'cat_id' => '234',
    'cat_name' => '刀剪砧板',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  200 => 
  array (
    'cat_id' => '239',
    'cat_name' => '枕芯枕套',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  201 => 
  array (
    'cat_id' => '237',
    'cat_name' => '床品件套',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  202 => 
  array (
    'cat_id' => '238',
    'cat_name' => '被子',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  203 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  204 => 
  array (
    'cat_id' => '249',
    'cat_name' => '裤子',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  205 => 
  array (
    'cat_id' => '247',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  206 => 
  array (
    'cat_id' => '251',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  207 => 
  array (
    'cat_id' => '252',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  208 => 
  array (
    'cat_id' => '253',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  209 => 
  array (
    'cat_id' => '261',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  210 => 
  array (
    'cat_id' => '262',
    'cat_name' => '精华露',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  211 => 
  array (
    'cat_id' => '260',
    'cat_name' => '洁面乳',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  212 => 
  array (
    'cat_id' => '264',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  213 => 
  array (
    'cat_id' => '265',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  214 => 
  array (
    'cat_id' => '266',
    'cat_name' => '香薰精油',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  215 => 
  array (
    'cat_id' => '328',
    'cat_name' => '保湿霜',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  216 => 
  array (
    'cat_id' => '329',
    'cat_name' => '防晒霜',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  217 => 
  array (
    'cat_id' => '359',
    'cat_name' => '双肩包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  218 => 
  array (
    'cat_id' => '274',
    'cat_name' => '手拿包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  219 => 
  array (
    'cat_id' => '360',
    'cat_name' => '斜挎包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  220 => 
  array (
    'cat_id' => '275',
    'cat_name' => '单肩包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  221 => 
  array (
    'cat_id' => '361',
    'cat_name' => '女士钱包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  222 => 
  array (
    'cat_id' => '273',
    'cat_name' => '钱包/卡包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  223 => 
  array (
    'cat_id' => '370',
    'cat_name' => '万向轮箱',
    'measure_unit' => '',
    'parent_id' => '279',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  224 => 
  array (
    'cat_id' => '369',
    'cat_name' => '旅行箱包',
    'measure_unit' => '',
    'parent_id' => '279',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  225 => 
  array (
    'cat_id' => '387',
    'cat_name' => '其他生活电器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  226 => 
  array (
    'cat_id' => '384',
    'cat_name' => '除湿干衣机',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  227 => 
  array (
    'cat_id' => '382',
    'cat_name' => '饮水净化器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  228 => 
  array (
    'cat_id' => '377',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  229 => 
  array (
    'cat_id' => '383',
    'cat_name' => '吸尘器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  230 => 
  array (
    'cat_id' => '386',
    'cat_name' => '加湿器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  231 => 
  array (
    'cat_id' => '380',
    'cat_name' => '冷风扇',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  232 => 
  array (
    'cat_id' => '385',
    'cat_name' => '电话机',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  233 => 
  array (
    'cat_id' => '379',
    'cat_name' => '电风扇',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  234 => 
  array (
    'cat_id' => '381',
    'cat_name' => '空气净化器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  235 => 
  array (
    'cat_id' => '390',
    'cat_name' => '咖啡机',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  236 => 
  array (
    'cat_id' => '388',
    'cat_name' => '豆浆机',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  237 => 
  array (
    'cat_id' => '391',
    'cat_name' => '榨汁机',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  238 => 
  array (
    'cat_id' => '389',
    'cat_name' => '面包机',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  239 => 
  array (
    'cat_id' => '392',
    'cat_name' => '电烤箱',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  240 => 
  array (
    'cat_id' => '393',
    'cat_name' => '煮蛋器',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  241 => 
  array (
    'cat_id' => '373',
    'cat_name' => '冰箱',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  242 => 
  array (
    'cat_id' => '375',
    'cat_name' => '酒柜冷柜',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  243 => 
  array (
    'cat_id' => '378',
    'cat_name' => '音响',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  244 => 
  array (
    'cat_id' => '374',
    'cat_name' => '洗衣机',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  245 => 
  array (
    'cat_id' => '372',
    'cat_name' => '空调',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  246 => 
  array (
    'cat_id' => '376',
    'cat_name' => '家庭影院',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  247 => 
  array (
    'cat_id' => '371',
    'cat_name' => '平板电视',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  248 => 
  array (
    'cat_id' => '318',
    'cat_name' => '软糖',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
  ),
  249 => 
  array (
    'cat_id' => '319',
    'cat_name' => '硬糖',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 26,
  ),
  250 => 
  array (
    'cat_id' => '336',
    'cat_name' => '果冻布丁',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
  ),
  251 => 
  array (
    'cat_id' => '317',
    'cat_name' => '奶糖',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  252 => 
  array (
    'cat_id' => '338',
    'cat_name' => '棒棒糖',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
  ),
  253 => 
  array (
    'cat_id' => '365',
    'cat_name' => '手包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  254 => 
  array (
    'cat_id' => '363',
    'cat_name' => '男士单肩包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  255 => 
  array (
    'cat_id' => '364',
    'cat_name' => '双肩包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  256 => 
  array (
    'cat_id' => '367',
    'cat_name' => '斜挎包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  257 => 
  array (
    'cat_id' => '368',
    'cat_name' => '腰包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  258 => 
  array (
    'cat_id' => '398',
    'cat_name' => '韩国',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  259 => 
  array (
    'cat_id' => '397',
    'cat_name' => '日本',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  260 => 
  array (
    'cat_id' => '403',
    'cat_name' => '泰国',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  261 => 
  array (
    'cat_id' => '402',
    'cat_name' => '印度',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  262 => 
  array (
    'cat_id' => '433',
    'cat_name' => '香港',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  263 => 
  array (
    'cat_id' => '399',
    'cat_name' => '越南',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  264 => 
  array (
    'cat_id' => '434',
    'cat_name' => '台湾',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  265 => 
  array (
    'cat_id' => '404',
    'cat_name' => '朝鲜',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  266 => 
  array (
    'cat_id' => '430',
    'cat_name' => '蒙古',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  267 => 
  array (
    'cat_id' => '400',
    'cat_name' => '东南亚',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  268 => 
  array (
    'cat_id' => '431',
    'cat_name' => '中亚',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  269 => 
  array (
    'cat_id' => '401',
    'cat_name' => '西亚',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  270 => 
  array (
    'cat_id' => '406',
    'cat_name' => '英国',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  271 => 
  array (
    'cat_id' => '408',
    'cat_name' => '德国',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  272 => 
  array (
    'cat_id' => '414',
    'cat_name' => '俄罗斯',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  273 => 
  array (
    'cat_id' => '411',
    'cat_name' => '南欧',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  274 => 
  array (
    'cat_id' => '412',
    'cat_name' => '北欧',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  275 => 
  array (
    'cat_id' => '409',
    'cat_name' => '西班牙',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  276 => 
  array (
    'cat_id' => '413',
    'cat_name' => '东欧',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  277 => 
  array (
    'cat_id' => '410',
    'cat_name' => '西欧',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  278 => 
  array (
    'cat_id' => '407',
    'cat_name' => '法国',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  279 => 
  array (
    'cat_id' => '416',
    'cat_name' => '澳大利亚',
    'measure_unit' => '',
    'parent_id' => '415',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  280 => 
  array (
    'cat_id' => '417',
    'cat_name' => '新西兰',
    'measure_unit' => '',
    'parent_id' => '415',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  281 => 
  array (
    'cat_id' => '421',
    'cat_name' => '南非',
    'measure_unit' => '',
    'parent_id' => '418',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  282 => 
  array (
    'cat_id' => '419',
    'cat_name' => '北非',
    'measure_unit' => '',
    'parent_id' => '418',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  283 => 
  array (
    'cat_id' => '420',
    'cat_name' => '中非',
    'measure_unit' => '',
    'parent_id' => '418',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  284 => 
  array (
    'cat_id' => '423',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '422',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  285 => 
  array (
    'cat_id' => '426',
    'cat_name' => '墨西哥',
    'measure_unit' => '',
    'parent_id' => '422',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  286 => 
  array (
    'cat_id' => '424',
    'cat_name' => '加拿大',
    'measure_unit' => '',
    'parent_id' => '422',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  287 => 
  array (
    'cat_id' => '427',
    'cat_name' => '巴西',
    'measure_unit' => '',
    'parent_id' => '432',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  288 => 
  array (
    'cat_id' => '428',
    'cat_name' => '阿根廷',
    'measure_unit' => '',
    'parent_id' => '432',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>