<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '食品、零食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => '32',
    'level' => 0,
    'id' => '1',
    'name' => '食品、零食',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '坚果果仁',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '坚果果仁',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '坚果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '30',
    'level' => 2,
    'id' => '14',
    'name' => '坚果',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '果仁',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 2,
    'id' => '15',
    'name' => '果仁',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '开心果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 2,
    'id' => '16',
    'name' => '开心果',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '腰果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 24,
    'level' => 2,
    'id' => '17',
    'name' => '腰果',
  ),
  330 => 
  array (
    'cat_id' => '330',
    'cat_name' => '杏仁',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
    'level' => 2,
    'id' => '330',
    'name' => '杏仁',
  ),
  331 => 
  array (
    'cat_id' => '331',
    'cat_name' => '夏威夷果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 2,
    'id' => '331',
    'name' => '夏威夷果',
  ),
  332 => 
  array (
    'cat_id' => '332',
    'cat_name' => '混合坚果',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '27',
    'level' => 2,
    'id' => '332',
    'name' => '混合坚果',
  ),
  316 => 
  array (
    'cat_id' => '316',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '316',
    'name' => '糖果',
  ),
  318 => 
  array (
    'cat_id' => '318',
    'cat_name' => '软糖',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
    'level' => 2,
    'id' => '318',
    'name' => '软糖',
  ),
  319 => 
  array (
    'cat_id' => '319',
    'cat_name' => '硬糖',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 26,
    'level' => 2,
    'id' => '319',
    'name' => '硬糖',
  ),
  336 => 
  array (
    'cat_id' => '336',
    'cat_name' => '果冻布丁',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
    'level' => 2,
    'id' => '336',
    'name' => '果冻布丁',
  ),
  317 => 
  array (
    'cat_id' => '317',
    'cat_name' => '奶糖',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 2,
    'id' => '317',
    'name' => '奶糖',
  ),
  338 => 
  array (
    'cat_id' => '338',
    'cat_name' => '棒棒糖',
    'measure_unit' => '',
    'parent_id' => '316',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 2,
    'id' => '338',
    'name' => '棒棒糖',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '罐头',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '75',
    'name' => '罐头',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '鱼罐头',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 2,
    'id' => '79',
    'name' => '鱼罐头',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '鱼子酱',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
    'level' => 2,
    'id' => '76',
    'name' => '鱼子酱',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '果酱',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 2,
    'id' => '77',
    'name' => '果酱',
  ),
  340 => 
  array (
    'cat_id' => '340',
    'cat_name' => '咖喱',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
    'level' => 2,
    'id' => '340',
    'name' => '咖喱',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '肉罐头',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 2,
    'id' => '78',
    'name' => '肉罐头',
  ),
  341 => 
  array (
    'cat_id' => '341',
    'cat_name' => '水果罐头',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '341',
    'name' => '水果罐头',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '零食',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '9',
    'level' => 1,
    'id' => '54',
    'name' => '零食',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '薯片',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '59',
    'name' => '薯片',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '海鲜零食',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '55',
    'name' => '海鲜零食',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '60',
    'name' => '巧克力',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '肉脯肉松',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '56',
    'name' => '肉脯肉松',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '膨化类',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '58',
    'name' => '膨化类',
  ),
  395 => 
  array (
    'cat_id' => '395',
    'cat_name' => '棒棒糖',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '395',
    'name' => '棒棒糖',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '饼干糕点',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '饼干糕点',
  ),
  339 => 
  array (
    'cat_id' => '339',
    'cat_name' => '威化饼',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '339',
    'name' => '威化饼',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '26',
    'name' => '曲奇',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '23',
    'name' => '饼干',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '西式糕点',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '27',
    'name' => '西式糕点',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '面包',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '巧克力派',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 2,
    'id' => '25',
    'name' => '巧克力派',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '饮料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => '饮料',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '豆浆',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '豆浆',
  ),
  342 => 
  array (
    'cat_id' => '342',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '342',
    'name' => '红茶',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '蜂蜜',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '奶茶',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '奶茶',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '咖啡',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '早餐谷物',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '早餐谷物',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '洋酒、葡萄酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => '30',
    'level' => 0,
    'id' => '2',
    'name' => '洋酒、葡萄酒',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '红普通酒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '红普通酒',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '干红',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 2,
    'id' => '81',
    'name' => '干红',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '半干红',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '85',
    'name' => '半干红',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '甜红',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '甜红',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '半甜红',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '82',
    'name' => '半甜红',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '106',
    'name' => '白葡萄酒',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '干白',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '111',
    'name' => '干白',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '半干白',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '108',
    'name' => '半干白',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '甜白',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '甜白',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '半甜白',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '半甜白',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '洋酒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '8',
    'goods_num' => '8',
    'level' => 1,
    'id' => '123',
    'name' => '洋酒',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '白兰地',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '124',
    'name' => '白兰地',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '伏特加',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '伏特加',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '威士忌',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '威士忌',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '龙舌兰',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '龙舌兰',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '金酒',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '金酒',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '朗姆酒',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '朗姆酒',
  ),
  344 => 
  array (
    'cat_id' => '344',
    'cat_name' => '清酒',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '344',
    'name' => '清酒',
  ),
  343 => 
  array (
    'cat_id' => '343',
    'cat_name' => '烧酒',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '343',
    'name' => '烧酒',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '啤酒',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '黑啤',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '黑啤',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '普通啤酒',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 2,
    'id' => '102',
    'name' => '普通啤酒',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '工艺品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '4',
    'has_children' => '2',
    'goods_num' => '31',
    'level' => 0,
    'id' => '3',
    'name' => '工艺品',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '特色工艺品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '171',
    'name' => '特色工艺品',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '木质工艺品',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '174',
    'name' => '木质工艺品',
  ),
  345 => 
  array (
    'cat_id' => '345',
    'cat_name' => '手工艺品',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '345',
    'name' => '手工艺品',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '金属工艺品',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '172',
    'name' => '金属工艺品',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '瓷器',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '173',
    'name' => '瓷器',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => '装饰品',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '200',
    'name' => '装饰品',
  ),
  205 => 
  array (
    'cat_id' => '205',
    'cat_name' => '地毯',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '205',
    'name' => '地毯',
  ),
  207 => 
  array (
    'cat_id' => '207',
    'cat_name' => '装饰器具',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '207',
    'name' => '装饰器具',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => '挂饰',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '202',
    'name' => '挂饰',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => '坐垫',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '206',
    'name' => '坐垫',
  ),
  203 => 
  array (
    'cat_id' => '203',
    'cat_name' => '编织装饰',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '203',
    'name' => '编织装饰',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '家电电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => '30',
    'level' => 0,
    'id' => '9',
    'name' => '家电电器',
  ),
  288 => 
  array (
    'cat_id' => '288',
    'cat_name' => '大家电',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '288',
    'name' => '大家电',
  ),
  373 => 
  array (
    'cat_id' => '373',
    'cat_name' => '冰箱',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '373',
    'name' => '冰箱',
  ),
  375 => 
  array (
    'cat_id' => '375',
    'cat_name' => '酒柜冷柜',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '375',
    'name' => '酒柜冷柜',
  ),
  378 => 
  array (
    'cat_id' => '378',
    'cat_name' => '音响',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '378',
    'name' => '音响',
  ),
  374 => 
  array (
    'cat_id' => '374',
    'cat_name' => '洗衣机',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '374',
    'name' => '洗衣机',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '空调',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '372',
    'name' => '空调',
  ),
  376 => 
  array (
    'cat_id' => '376',
    'cat_name' => '家庭影院',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '376',
    'name' => '家庭影院',
  ),
  371 => 
  array (
    'cat_id' => '371',
    'cat_name' => '平板电视',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '371',
    'name' => '平板电视',
  ),
  285 => 
  array (
    'cat_id' => '285',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 1,
    'id' => '285',
    'name' => '生活电器',
  ),
  387 => 
  array (
    'cat_id' => '387',
    'cat_name' => '其他生活电器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '387',
    'name' => '其他生活电器',
  ),
  384 => 
  array (
    'cat_id' => '384',
    'cat_name' => '除湿干衣机',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '384',
    'name' => '除湿干衣机',
  ),
  382 => 
  array (
    'cat_id' => '382',
    'cat_name' => '饮水净化器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '382',
    'name' => '饮水净化器',
  ),
  377 => 
  array (
    'cat_id' => '377',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '377',
    'name' => '热水器',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '吸尘器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '383',
    'name' => '吸尘器',
  ),
  386 => 
  array (
    'cat_id' => '386',
    'cat_name' => '加湿器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '386',
    'name' => '加湿器',
  ),
  380 => 
  array (
    'cat_id' => '380',
    'cat_name' => '冷风扇',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '380',
    'name' => '冷风扇',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '电话机',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '385',
    'name' => '电话机',
  ),
  379 => 
  array (
    'cat_id' => '379',
    'cat_name' => '电风扇',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '379',
    'name' => '电风扇',
  ),
  381 => 
  array (
    'cat_id' => '381',
    'cat_name' => '空气净化器',
    'measure_unit' => '',
    'parent_id' => '285',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '381',
    'name' => '空气净化器',
  ),
  287 => 
  array (
    'cat_id' => '287',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '287',
    'name' => '厨房电器',
  ),
  390 => 
  array (
    'cat_id' => '390',
    'cat_name' => '咖啡机',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '390',
    'name' => '咖啡机',
  ),
  388 => 
  array (
    'cat_id' => '388',
    'cat_name' => '豆浆机',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '388',
    'name' => '豆浆机',
  ),
  391 => 
  array (
    'cat_id' => '391',
    'cat_name' => '榨汁机',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '391',
    'name' => '榨汁机',
  ),
  389 => 
  array (
    'cat_id' => '389',
    'cat_name' => '面包机',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '389',
    'name' => '面包机',
  ),
  392 => 
  array (
    'cat_id' => '392',
    'cat_name' => '电烤箱',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '392',
    'name' => '电烤箱',
  ),
  393 => 
  array (
    'cat_id' => '393',
    'cat_name' => '煮蛋器',
    'measure_unit' => '',
    'parent_id' => '287',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '393',
    'name' => '煮蛋器',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '健康电器',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 1,
    'id' => '130',
    'name' => '健康电器',
  ),
  394 => 
  array (
    'cat_id' => '394',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '394',
    'name' => '剃须刀',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '其它健康电器',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '其它健康电器',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '血糖仪',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '血糖仪',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '足浴盆',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '133',
    'name' => '足浴盆',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '体温计',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '体温计',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '血压计',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '134',
    'name' => '血压计',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '按摩器',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '131',
    'name' => '按摩器',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '计步器/脂肪检测仪',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '138',
    'name' => '计步器/脂肪检测仪',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '健康秤/厨房秤',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '健康秤/厨房秤',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '按摩椅',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '132',
    'name' => '按摩椅',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '美妆、化妆品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => '31',
    'level' => 0,
    'id' => '4',
    'name' => '美妆、化妆品',
  ),
  208 => 
  array (
    'cat_id' => '208',
    'cat_name' => '护肤',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '208',
    'name' => '护肤',
  ),
  210 => 
  array (
    'cat_id' => '210',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '210',
    'name' => '洁面',
  ),
  348 => 
  array (
    'cat_id' => '348',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '348',
    'name' => '面膜',
  ),
  211 => 
  array (
    'cat_id' => '211',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '211',
    'name' => '精华',
  ),
  349 => 
  array (
    'cat_id' => '349',
    'cat_name' => '护肤套装',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '349',
    'name' => '护肤套装',
  ),
  346 => 
  array (
    'cat_id' => '346',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '346',
    'name' => '面霜',
  ),
  350 => 
  array (
    'cat_id' => '350',
    'cat_name' => '化妆水',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '350',
    'name' => '化妆水',
  ),
  209 => 
  array (
    'cat_id' => '209',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '209',
    'name' => '乳液',
  ),
  347 => 
  array (
    'cat_id' => '347',
    'cat_name' => '眼霜',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '347',
    'name' => '眼霜',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => '彩妆',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '212',
    'name' => '彩妆',
  ),
  354 => 
  array (
    'cat_id' => '354',
    'cat_name' => '唇彩',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '354',
    'name' => '唇彩',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '213',
    'name' => '防晒',
  ),
  351 => 
  array (
    'cat_id' => '351',
    'cat_name' => '粉饼',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '351',
    'name' => '粉饼',
  ),
  355 => 
  array (
    'cat_id' => '355',
    'cat_name' => '彩妆套装',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '355',
    'name' => '彩妆套装',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => 'BB霜',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '214',
    'name' => 'BB霜',
  ),
  352 => 
  array (
    'cat_id' => '352',
    'cat_name' => '眼影',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '352',
    'name' => '眼影',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => '卸妆',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '215',
    'name' => '卸妆',
  ),
  353 => 
  array (
    'cat_id' => '353',
    'cat_name' => '睫毛膏',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '353',
    'name' => '睫毛膏',
  ),
  224 => 
  array (
    'cat_id' => '224',
    'cat_name' => '香氛',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '224',
    'name' => '香氛',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => '打印机',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '225',
    'name' => '打印机',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => '女士香水',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '226',
    'name' => '女士香水',
  ),
  356 => 
  array (
    'cat_id' => '356',
    'cat_name' => '香水套装',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '356',
    'name' => '香水套装',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => '中性香水',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '227',
    'name' => '中性香水',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => '身体护理',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '220',
    'name' => '身体护理',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '222',
    'name' => '护发',
  ),
  357 => 
  array (
    'cat_id' => '357',
    'cat_name' => '脱毛',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '357',
    'name' => '脱毛',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => '润肤乳',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '223',
    'name' => '润肤乳',
  ),
  358 => 
  array (
    'cat_id' => '358',
    'cat_name' => '护理套装',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '358',
    'name' => '护理套装',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => '洗发',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '221',
    'name' => '洗发',
  ),
  324 => 
  array (
    'cat_id' => '324',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '324',
    'name' => '沐浴',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '家居、家具、厨具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '8',
    'goods_num' => '31',
    'level' => 0,
    'id' => '5',
    'name' => '家居、家具、厨具',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '232',
    'name' => '厨具',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => '收纳保鲜',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '235',
    'name' => '收纳保鲜',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '233',
    'name' => '烹饪锅具',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => '刀剪砧板',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '234',
    'name' => '刀剪砧板',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '家装建材',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '245',
    'name' => '家装建材',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => '生活日用',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '242',
    'name' => '生活日用',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '236',
    'name' => '家纺',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => '枕芯枕套',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '239',
    'name' => '枕芯枕套',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => '床品件套',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '237',
    'name' => '床品件套',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => '被子',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '238',
    'name' => '被子',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '243',
    'name' => '清洁用品',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '240',
    'name' => '家具',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '宠物用品',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '244',
    'name' => '宠物用品',
  ),
  241 => 
  array (
    'cat_id' => '241',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '241',
    'name' => '灯具',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '服饰鞋帽',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => '31',
    'level' => 0,
    'id' => '6',
    'name' => '服饰鞋帽',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => '个护化妆',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '246',
    'name' => '个护化妆',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '248',
    'name' => 'T恤',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => '裤子',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '249',
    'name' => '裤子',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '247',
    'name' => '衬衫',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => '鞋靴箱包',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '250',
    'name' => '鞋靴箱包',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '251',
    'name' => '衬衫',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '252',
    'name' => 'T恤',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => '连衣裙',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '253',
    'name' => '连衣裙',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => '时尚搭配',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '257',
    'name' => '时尚搭配',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => '女士健康',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '254',
    'name' => '女士健康',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => '棉服',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '258',
    'name' => '棉服',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => '内衣',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '255',
    'name' => '内衣',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '256',
    'name' => '配饰',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '个护化妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '个护化妆',
  ),
  269 => 
  array (
    'cat_id' => '269',
    'cat_name' => '男士护理',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '269',
    'name' => '男士护理',
  ),
  267 => 
  array (
    'cat_id' => '267',
    'cat_name' => '运动户外',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '267',
    'name' => '运动户外',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => '香水SPA',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '271',
    'name' => '香水SPA',
  ),
  268 => 
  array (
    'cat_id' => '268',
    'cat_name' => '女性护理',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '268',
    'name' => '女性护理',
  ),
  328 => 
  array (
    'cat_id' => '328',
    'cat_name' => '保湿霜',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '328',
    'name' => '保湿霜',
  ),
  329 => 
  array (
    'cat_id' => '329',
    'cat_name' => '防晒霜',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '329',
    'name' => '防晒霜',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => '营养健康',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '1',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '259',
    'name' => '营养健康',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '261',
    'name' => '爽肤水',
  ),
  262 => 
  array (
    'cat_id' => '262',
    'cat_name' => '精华露',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '262',
    'name' => '精华露',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => '洁面乳',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '260',
    'name' => '洁面乳',
  ),
  263 => 
  array (
    'cat_id' => '263',
    'cat_name' => '型男搭配',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '263',
    'name' => '型男搭配',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '264',
    'name' => '洗发护发',
  ),
  265 => 
  array (
    'cat_id' => '265',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '265',
    'name' => '沐浴',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => '香薰精油',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '266',
    'name' => '香薰精油',
  ),
  270 => 
  array (
    'cat_id' => '270',
    'cat_name' => '魅力彩妆',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '270',
    'name' => '魅力彩妆',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '国外箱包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => '32',
    'level' => 0,
    'id' => '8',
    'name' => '国外箱包',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '潮流女包',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '272',
    'name' => '潮流女包',
  ),
  359 => 
  array (
    'cat_id' => '359',
    'cat_name' => '双肩包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '359',
    'name' => '双肩包',
  ),
  274 => 
  array (
    'cat_id' => '274',
    'cat_name' => '手拿包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '274',
    'name' => '手拿包',
  ),
  360 => 
  array (
    'cat_id' => '360',
    'cat_name' => '斜挎包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '360',
    'name' => '斜挎包',
  ),
  275 => 
  array (
    'cat_id' => '275',
    'cat_name' => '单肩包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '275',
    'name' => '单肩包',
  ),
  361 => 
  array (
    'cat_id' => '361',
    'cat_name' => '女士钱包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '361',
    'name' => '女士钱包',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '钱包/卡包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '273',
    'name' => '钱包/卡包',
  ),
  362 => 
  array (
    'cat_id' => '362',
    'cat_name' => '男士包',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '362',
    'name' => '男士包',
  ),
  365 => 
  array (
    'cat_id' => '365',
    'cat_name' => '手包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '365',
    'name' => '手包',
  ),
  363 => 
  array (
    'cat_id' => '363',
    'cat_name' => '男士单肩包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '363',
    'name' => '男士单肩包',
  ),
  364 => 
  array (
    'cat_id' => '364',
    'cat_name' => '双肩包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '364',
    'name' => '双肩包',
  ),
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '斜挎包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '367',
    'name' => '斜挎包',
  ),
  368 => 
  array (
    'cat_id' => '368',
    'cat_name' => '腰包',
    'measure_unit' => '',
    'parent_id' => '362',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '368',
    'name' => '腰包',
  ),
  279 => 
  array (
    'cat_id' => '279',
    'cat_name' => '功能箱包',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '279',
    'name' => '功能箱包',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '万向轮箱',
    'measure_unit' => '',
    'parent_id' => '279',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '370',
    'name' => '万向轮箱',
  ),
  369 => 
  array (
    'cat_id' => '369',
    'cat_name' => '旅行箱包',
    'measure_unit' => '',
    'parent_id' => '279',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '369',
    'name' => '旅行箱包',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '母婴、玩具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '10',
    'name' => '母婴、玩具',
  ),
  298 => 
  array (
    'cat_id' => '298',
    'cat_name' => '寝具服饰',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '298',
    'name' => '寝具服饰',
  ),
  295 => 
  array (
    'cat_id' => '295',
    'cat_name' => '喂养用品',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '295',
    'name' => '喂养用品',
  ),
  292 => 
  array (
    'cat_id' => '292',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '292',
    'name' => '奶粉',
  ),
  299 => 
  array (
    'cat_id' => '299',
    'cat_name' => '妈妈专区',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '299',
    'name' => '妈妈专区',
  ),
  296 => 
  array (
    'cat_id' => '296',
    'cat_name' => '洗护用品',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '296',
    'name' => '洗护用品',
  ),
  293 => 
  array (
    'cat_id' => '293',
    'cat_name' => '营养辅食',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '293',
    'name' => '营养辅食',
  ),
  300 => 
  array (
    'cat_id' => '300',
    'cat_name' => '玩具乐器',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '300',
    'name' => '玩具乐器',
  ),
  297 => 
  array (
    'cat_id' => '297',
    'cat_name' => '童车童床',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '297',
    'name' => '童车童床',
  ),
  294 => 
  array (
    'cat_id' => '294',
    'cat_name' => '尿裤湿巾',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '294',
    'name' => '尿裤湿巾',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '食品饮料、保健食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '11',
    'name' => '食品饮料、保健食品',
  ),
  301 => 
  array (
    'cat_id' => '301',
    'cat_name' => '进口食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '301',
    'name' => '进口食品',
  ),
  308 => 
  array (
    'cat_id' => '308',
    'cat_name' => '健康礼品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '308',
    'name' => '健康礼品',
  ),
  305 => 
  array (
    'cat_id' => '305',
    'cat_name' => '酒饮冲调',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '305',
    'name' => '酒饮冲调',
  ),
  302 => 
  array (
    'cat_id' => '302',
    'cat_name' => '地方特产',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '302',
    'name' => '地方特产',
  ),
  309 => 
  array (
    'cat_id' => '309',
    'cat_name' => '生鲜食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '309',
    'name' => '生鲜食品',
  ),
  306 => 
  array (
    'cat_id' => '306',
    'cat_name' => '营养健康',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '306',
    'name' => '营养健康',
  ),
  303 => 
  array (
    'cat_id' => '303',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '303',
    'name' => '休闲食品',
  ),
  307 => 
  array (
    'cat_id' => '307',
    'cat_name' => '亚健康',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '307',
    'name' => '亚健康',
  ),
  304 => 
  array (
    'cat_id' => '304',
    'cat_name' => '粮油调味',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '304',
    'name' => '粮油调味',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '彩票、旅行、充值',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '彩票、旅行、充值',
  ),
  314 => 
  array (
    'cat_id' => '314',
    'cat_name' => '票务',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '314',
    'name' => '票务',
  ),
  311 => 
  array (
    'cat_id' => '311',
    'cat_name' => '机票',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '311',
    'name' => '机票',
  ),
  312 => 
  array (
    'cat_id' => '312',
    'cat_name' => '酒店',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '312',
    'name' => '酒店',
  ),
  313 => 
  array (
    'cat_id' => '313',
    'cat_name' => '充值',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '313',
    'name' => '充值',
  ),
  310 => 
  array (
    'cat_id' => '310',
    'cat_name' => '彩票',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '310',
    'name' => '彩票',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '汽车用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '16',
    'goods_num' => 0,
    'level' => 0,
    'id' => '154',
    'name' => '汽车用品',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '脚垫',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '161',
    'name' => '脚垫',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '车载电源',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '158',
    'name' => '车载电源',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => 'GPS',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '155',
    'name' => 'GPS',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '安全座椅',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '168',
    'name' => '安全座椅',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '内饰',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '165',
    'name' => '内饰',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '座垫座套',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '162',
    'name' => '座垫座套',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '充气/吸尘',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '159',
    'name' => '充气/吸尘',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '电子影音',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '156',
    'name' => '电子影音',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '自驾装备',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '169',
    'name' => '自驾装备',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '配件',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '166',
    'name' => '配件',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '养护',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '163',
    'name' => '养护',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '冷暖箱',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '160',
    'name' => '冷暖箱',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '车载电器',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '157',
    'name' => '车载电器',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '安全/应急',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '170',
    'name' => '安全/应急',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '香水/净化',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '167',
    'name' => '香水/净化',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '美容',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '164',
    'name' => '美容',
  ),
  405 => 
  array (
    'cat_id' => '405',
    'cat_name' => '欧 洲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '405',
    'name' => '欧 洲',
  ),
  406 => 
  array (
    'cat_id' => '406',
    'cat_name' => '英国',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '406',
    'name' => '英国',
  ),
  408 => 
  array (
    'cat_id' => '408',
    'cat_name' => '德国',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '408',
    'name' => '德国',
  ),
  414 => 
  array (
    'cat_id' => '414',
    'cat_name' => '俄罗斯',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '414',
    'name' => '俄罗斯',
  ),
  411 => 
  array (
    'cat_id' => '411',
    'cat_name' => '南欧',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '411',
    'name' => '南欧',
  ),
  412 => 
  array (
    'cat_id' => '412',
    'cat_name' => '北欧',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '412',
    'name' => '北欧',
  ),
  409 => 
  array (
    'cat_id' => '409',
    'cat_name' => '西班牙',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '409',
    'name' => '西班牙',
  ),
  413 => 
  array (
    'cat_id' => '413',
    'cat_name' => '东欧',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '413',
    'name' => '东欧',
  ),
  410 => 
  array (
    'cat_id' => '410',
    'cat_name' => '西欧',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '410',
    'name' => '西欧',
  ),
  407 => 
  array (
    'cat_id' => '407',
    'cat_name' => '法国',
    'measure_unit' => '',
    'parent_id' => '405',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '407',
    'name' => '法国',
  ),
  418 => 
  array (
    'cat_id' => '418',
    'cat_name' => '非 洲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '418',
    'name' => '非 洲',
  ),
  421 => 
  array (
    'cat_id' => '421',
    'cat_name' => '南非',
    'measure_unit' => '',
    'parent_id' => '418',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '421',
    'name' => '南非',
  ),
  419 => 
  array (
    'cat_id' => '419',
    'cat_name' => '北非',
    'measure_unit' => '',
    'parent_id' => '418',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '419',
    'name' => '北非',
  ),
  420 => 
  array (
    'cat_id' => '420',
    'cat_name' => '中非',
    'measure_unit' => '',
    'parent_id' => '418',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '420',
    'name' => '中非',
  ),
  396 => 
  array (
    'cat_id' => '396',
    'cat_name' => '亚 洲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '12',
    'goods_num' => 0,
    'level' => 0,
    'id' => '396',
    'name' => '亚 洲',
  ),
  398 => 
  array (
    'cat_id' => '398',
    'cat_name' => '韩国',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '398',
    'name' => '韩国',
  ),
  397 => 
  array (
    'cat_id' => '397',
    'cat_name' => '日本',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '397',
    'name' => '日本',
  ),
  403 => 
  array (
    'cat_id' => '403',
    'cat_name' => '泰国',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '403',
    'name' => '泰国',
  ),
  402 => 
  array (
    'cat_id' => '402',
    'cat_name' => '印度',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '402',
    'name' => '印度',
  ),
  433 => 
  array (
    'cat_id' => '433',
    'cat_name' => '香港',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '433',
    'name' => '香港',
  ),
  399 => 
  array (
    'cat_id' => '399',
    'cat_name' => '越南',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '399',
    'name' => '越南',
  ),
  434 => 
  array (
    'cat_id' => '434',
    'cat_name' => '台湾',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '434',
    'name' => '台湾',
  ),
  404 => 
  array (
    'cat_id' => '404',
    'cat_name' => '朝鲜',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '404',
    'name' => '朝鲜',
  ),
  430 => 
  array (
    'cat_id' => '430',
    'cat_name' => '蒙古',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '430',
    'name' => '蒙古',
  ),
  400 => 
  array (
    'cat_id' => '400',
    'cat_name' => '东南亚',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '400',
    'name' => '东南亚',
  ),
  431 => 
  array (
    'cat_id' => '431',
    'cat_name' => '中亚',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '431',
    'name' => '中亚',
  ),
  401 => 
  array (
    'cat_id' => '401',
    'cat_name' => '西亚',
    'measure_unit' => '',
    'parent_id' => '396',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '401',
    'name' => '西亚',
  ),
  422 => 
  array (
    'cat_id' => '422',
    'cat_name' => '北美',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '422',
    'name' => '北美',
  ),
  423 => 
  array (
    'cat_id' => '423',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '422',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '423',
    'name' => '美国',
  ),
  426 => 
  array (
    'cat_id' => '426',
    'cat_name' => '墨西哥',
    'measure_unit' => '',
    'parent_id' => '422',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '426',
    'name' => '墨西哥',
  ),
  424 => 
  array (
    'cat_id' => '424',
    'cat_name' => '加拿大',
    'measure_unit' => '',
    'parent_id' => '422',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '424',
    'name' => '加拿大',
  ),
  415 => 
  array (
    'cat_id' => '415',
    'cat_name' => '澳洲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '415',
    'name' => '澳洲',
  ),
  416 => 
  array (
    'cat_id' => '416',
    'cat_name' => '澳大利亚',
    'measure_unit' => '',
    'parent_id' => '415',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '416',
    'name' => '澳大利亚',
  ),
  417 => 
  array (
    'cat_id' => '417',
    'cat_name' => '新西兰',
    'measure_unit' => '',
    'parent_id' => '415',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '417',
    'name' => '新西兰',
  ),
  432 => 
  array (
    'cat_id' => '432',
    'cat_name' => '南美',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '432',
    'name' => '南美',
  ),
  427 => 
  array (
    'cat_id' => '427',
    'cat_name' => '巴西',
    'measure_unit' => '',
    'parent_id' => '432',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '427',
    'name' => '巴西',
  ),
  428 => 
  array (
    'cat_id' => '428',
    'cat_name' => '阿根廷',
    'measure_unit' => '',
    'parent_id' => '432',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '428',
    'name' => '阿根廷',
  ),
);
?>